data:
  population_max_size: 10000
  number_of_llm_based_agents: 10000

gtfs:
  cache_enabled: false
  mode: OTP

agent:
  reschedule_activity_departure_time: false
  long_term_memory_enabled: false
  quantify_time_window: false
  long_term_reflect_interval: 86400
  pre_schedule_duration: 3600
