
gtfs:
  cache_enabled: false
  mode: OTP
  max_trip_candidates: 3

agent:
  reschedule_activity_departure_time: true
  quantify_time_window: false
  long_term_reflect_interval: 86400
  long_term_max_entries_query: 10

