
gtfs:
  recursion_search_depth: 0
  cache_enabled: false
  trip_query_range: [0, 15, -15]
  max_trip_candidates: 5

agent:
  reschedule_activity_departure_time: false
  quantify_time_window: true
  long_term_max_entries_query: 12
  long_term_reflect_interval: 43200  # 12 hours

